[package]
name = "lab-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
include_dir.workspace = true
duckdb.workspace = true
lab-core = { path = "../lab-core" }
